version: '2'
services:
  apicurio:
    image: apicurio/apicurio-registry-mem:2.0.0.Final
    ports:
      - 8080:8080
  connect:
    image: arawa3/msk-s3-connector:1.0
    build:
      context: ./s3-sink-connector
    ports:
      - 8083:8083
    links:
      - apicurio
    environment:
      - BOOTSTRAP_SERVERS=b-1.mskclustermskconnectl.kor5wp.c23.kafka.us-east-1.amazonaws.com:9092,b-3.mskclustermskconnectl.kor5wp.c23.kafka.us-east-1.amazonaws.com:9092,b-2.mskclustermskconnectl.kor5wp.c23.kafka.us-east-1.amazonaws.com:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=new_connect_configs3
      - CONFIG_STORAGE_TOPIC_REPLICATION_FACTOR=3
      - OFFSET_STORAGE_TOPIC=new_connect_offsets3
      - OFFSET_STORAGE_TOPIC_REPLICATION_FACTOR=3
      - STATUS_STORAGE_TOPIC=new_connect_statuses3
      - STATUS_STORAGE_TOPIC_REPLICATION_FACTOR=3
      - ENABLE_APICURIO_CONVERTERS=true

